# yaml 配置
version: "2.2"
services:
  mysql3306:
    image: "mysql/mysql-server:5.7"
    ports:
      - "3306:3306"
#    command: "--default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: "zhaolu123"
      MYSQL_DATABASE: "pink"
      MYSQL_PASSWORD: "zhaolu123"
#    volumes:
#      - ./init.sql:/data/application/init.sql
  redis6379:
    image: "redis:5.0.7"
    ports:
      - "6379:6379"
#  pink_app:
#    build: .
#    command: sh -c "./wait-for.sh mysql3306:3306 redis6379:6379 -- ./pinkacg ./config.yaml"
#    depends_on:
#      - mysql3306
#      - redis6379
#    ports:
#      - "8080:8888"